version: '3.8'

services:
  web:
    build: .
    container_name: hcmute-chatbot
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped 